port:  5001
sitename: Booster2
repo: "https://github.com/Booster2/Booster2"
wiki: "https://github.com/Booster2/Booster2/wiki"
tracker: "https://github.com/Booster2/Booster2/issues"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
